config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :watchlists

  root 'users#login'

  resources :users
  get 'login', to: 'users#login'
  post 'login', to: 'users#authenticate'
  get 'logout', to: 'users#logout'


  resources :movies do
    resources :reviews, only: [:index, :new, :create] # Include new and create actions for reviews
  end

  # Custom route for searching movies
  get '/search_movies', to: 'movies#search', as: 'search_movies'
  get '/search', to: 'movies#search', as: 'search'

  resources :seens, except: [:create, :destroy]
  post '/seens', to: 'seens#create', as: 'create_seen'
  delete '/seens/:id', to: 'seens#destroy', as: 'destroy_seen'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController
  before_action :set_watchlist, only: %i[ show edit update destroy ]

  # GET /watchlists or /watchlists.json
  def index
    sort_by = case params[:sort]
    when "asc" then "ORDER BY title ASC"
    when "desc" then "ORDER BY title DESC"
    when "highest_rating" then "ORDER BY user_rating DESC NULLS LAST"
    when "lowest_rating" then "ORDER BY user_rating ASC NULLS LAST"
    when "earliest_year" then "ORDER BY year ASC"
    when "latest_year" then "ORDER BY year DESC"
    else ""
    end
    @watchlists = ActiveRecord::Base.connection.exec_query("
    SELECT s.*, m.*
    FROM watchlist s
    LEFT JOIN movie m ON s.movieid = m.movieid
    WHERE s.userid = #{@current_user.userid}
    #{sort_by}
    ")
  end

  # GET /watchlists/1 or /watchlists/1.json
  def show
  end

  # GET /watchlists/new
  def new
    @watchlist = Watchlist.new
  end

  # GET /watchlists/1/edit
  def edit
  end

  # POST /watchlists or /watchlists.json
  def create
    @watchlist = Watchlist.new(watchlist_params)

    respond_to do |format|
      if @watchlist.save
        format.html { redirect_back(fallback_location: watchlists_url) }
      format.json { head :no_content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @watchlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /watchlists/1 or /watchlists/1.json
  def update
    respond_to do |format|
      if @watchlist.update(watchlist_params)
        format.html { redirect_to watchlist_url(@watchlist)}
        format.json { render :show, status: :ok, location: @watchlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @watchlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /watchlists/1 or /watchlists/1.json
  def destroy
    @watchlist.destroy!
    respond_to do |format|
      format.html { redirect_back(fallback_location: watchlists_url, notice: "watchlist was dd destroyed.") }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watchlist
      @watchlist = Watchlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def watchlist_params
      params.permit(:userid, :movieid)
    end
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/watchlists/_form.html.erb
<%= form_with(model: watchlist) do |form| %>
  <% if watchlist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(watchlist.errors.count, "error") %> prohibited this watchlist from being saved:</h2>

      <ul>
        <% watchlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :movie_id %>
    <%= form.number_field :movie_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/watchlists/_watchlist.html.erb
<div id="<%= dom_id watchlist %>">
</div>

app/views/watchlists/edit.html.erb
<h1>Editing watchlist</h1>

<%= render "form", watchlist: @watchlist %>

<br>

<div>
  <%= link_to "Show this watchlist", @watchlist %> |
  <%= link_to "Back to watchlists", watchlists_path %>
</div>

app/views/watchlists/index.html.erb
<p style="color: green"><%= notice %></p>



<div class="container">
  <h1 class = "my-4">My Watchlist</h1>

  <div class="button-container">
    <%= link_to "Order Added", watchlists_path(sort: "orderadded"), class: "btn btn-primary" %>
    <%= link_to "Sort A-Z", watchlists_path(sort: "asc"), class: "btn btn-primary" %>
    <%= link_to "Sort Z-A", watchlists_path(sort: "desc"), class: "btn btn-primary" %>
    <%= link_to "Earliest Release Year", watchlists_path(sort: "earliest_year"), class: "btn btn-primary" %>
    <%= link_to "Latest Release Year", watchlists_path(sort: "latest_year"), class: "btn btn-primary" %>
  </div>
  
  <div class="row">
    <% @watchlists.each_with_index do |watchlist, index| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-body">
            <h5 class="card-title"><%= watchlist['title'] %> (<%= watchlist['year'] %>)</h5>
          <div class="button-container">
  <%= link_to "View Details", movie_path(watchlist['movieid']), class: "btn btn-primary" %>
  
  <%= form_tag('/seens', method: :post) do %>
    <%= hidden_field_tag :userid, @current_user.userid %>
    <%= hidden_field_tag :movieid, watchlist['movieid'] %>
    <%= hidden_field_tag :watchdate, Time.now.strftime("%Y-%m-%d") %>
    <%= submit_tag "Mark as Seen", class: "btn btn-primary mark-as-seen-button" %>
  <% end %>
   <%= form_tag(watchlist_path(Watchlist.find(watchlist['watchlistid'])), method: :delete) do %>
      <%= submit_tag "Remove", class: "btn btn-primary mark-as-seen-button" %>
    <% end %>
</div>
</div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/watchlists/new.html.erb
<h1>New Entry to Watchlist</h1>

<%= render "form", watchlist: @watchlist %>

<br>

<div>
  <%= link_to "Back to watchlists", watchlists_path %>
</div>

app/views/watchlists/show.html.erb
<p style="color: green"><%= notice %></p>

<% if @watchlist.present? %>
  <h2>Watchlist Details</h2>
  <ul>
   
      <li><%= @watchlist.movieid %></li>
  
  </ul>
<% end %>

<div>
  <%= link_to "Edit this watchlist", edit_watchlist_path(@watchlist) %> |
  <%= link_to "Back to watchlists", watchlists_path %>

  <%= button_to "Destroy this watchlist", @watchlist, method: :delete %>
</div>