config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :watchlists

  root 'users#login'

  resources :users
  get 'login', to: 'users#login'
  post 'login', to: 'users#authenticate'
  get 'logout', to: 'users#logout'


  resources :movies do
    resources :reviews, only: [:index, :new, :create] # Include new and create actions for reviews
  end

  # Custom route for searching movies
  get '/search_movies', to: 'movies#search', as: 'search_movies'
  get '/search', to: 'movies#search', as: 'search'

  resources :seens, except: [:create, :destroy]
  post '/seens', to: 'seens#create', as: 'create_seen'
  delete '/seens/:id', to: 'seens#destroy', as: 'destroy_seen'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    num_seen(params[:id])
    num_watchlist(params[:id])
    avg_rating(params[:id])
    fav_actor(params[:id])
    fav_director(params[:id])
    top_genres(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def login
  end

  def authenticate
    user = User.find_by(name: params[:name])
    if user && user.password == params[:password]
      session[:user_id] = user.id
      redirect_to user_path(user.userid), notice: 'Logged in successfully!'
      puts "SUCCESS LOGIN"
    else
      flash[:alert] = 'Invalid name or password, please try again'
      puts flash[:alert]
      redirect_to login_url
    end
  end

  def logout
    session[:user_id] = nil
    @current_user = session[:user_id]
    redirect_to root_url, notice: 'Logged out successfully!'
  end

  def num_seen(userid)
    query = "SELECT COUNT(*) AS num_seen
              FROM Movie m
              JOIN Seen s ON m.MovieiD = s.movieid
              WHERE s.userid = '#{userid}';"
    result = ActiveRecord::Base.connection.execute(query)
    @num_seen = result.first['num_seen'].to_i
  end

  def num_watchlist(userid)
    query = "SELECT COUNT(*) AS num_seen
              FROM Movie m
              JOIN Watchlist s ON m.MovieiD = s.movieid
              WHERE s.userid = '#{userid}';"
    result = ActiveRecord::Base.connection.execute(query)
    @num_watchlist = result.first['num_seen'].to_i
  end

  def avg_rating(userid)
    query = "SELECT AVG(rating) AS avg
              FROM Review
              WHERE userid = '#{userid}';"
    result = ActiveRecord::Base.connection.execute(query)
    @avg_rating = result.first['avg'].to_f
  end

  def fav_actor(userid)
    query = "SELECT Actor.name, COUNT(*) AS appearances
              FROM Actor
              JOIN MovieActor ON Actor.actorid = MovieActor.actorid
              JOIN movie ON Movieactor.movieid = movie.movieid
              JOIN seen ON movie.movieid = seen.movieid
              WHERE seen.userid = '#{userid}'
              GROUP BY actor.name
              ORDER BY appearances DESC
              LIMIT 1;"
    result = ActiveRecord::Base.connection.execute(query)
    @fav_actor = result.to_a
  end

  def fav_director(userid)
    query = "SELECT movie.director, COUNT(*) AS num_movies_seen
              FROM movie
              JOIN seen ON movie.movieid = seen.movieid
              WHERE seen.userid = '#{userid}'
              GROUP BY movie.director
              ORDER BY num_movies_seen DESC
              LIMIT 1;"
    result = ActiveRecord::Base.connection.execute(query)
    @fav_director = result.to_a
  end

  def top_genres(userid)
    query = "SELECT genre.name, COUNT(*) AS num_movies_seen
              FROM genre
              JOIN Moviegenre ON genre.genreid = Moviegenre.genreid
              JOIN movie ON Moviegenre.movieid = movie.movieid
              JOIN seen ON movie.movieid = seen.movieid
              WHERE seen.userid = '#{userid}'
              GROUP BY genre.name
              ORDER BY num_movies_seen DESC
              LIMIT 3;"
    result = ActiveRecord::Base.connection.execute(query)
    @top_genres = result.to_a
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # app/controllers/users_controller.rb
def user_params
  params.require(:user).permit(:name, :email, :password)
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1>My Movie Tracker</h1>
    <div class="col-md-6">
      <h1>Login</h1>

      <%= form_with(url: login_path, method: :post, class: "mt-4") do |form| %>
        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :password %>
          <%= form.password_field :password, class: "form-control" %>
        </div>

        <div class="text-center">
          <%= form.submit 'Login', class: "btn btn-primary" %>
        </div>
      <% end %>

      <br>

      <div class="text-center">
        <%= link_to "Sign up", new_user_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to login", root_url %>
</div>

app/views/users/show.html.erb
<div class="container">

  <% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

  <h1 class="my-4">My Stats</h1>

  <div class="row">
    <div class="col-md-6">
      <p>
        <strong>Total Movies Seen:</strong>
        <%= @num_seen %>
      </p>
      <p>
        <strong>Total Movies in Watchlist:</strong>
        <%= @num_watchlist %>
      </p>
      <p>
        <strong>Average Rating:</strong>
        <%= @avg_rating.round(2) %>
      </p>
     <% if @fav_actor.present? %>
        <p>
          <strong>Favorite Actor:</strong>
          <%= @fav_actor.first['name'] %> (<%= @fav_actor.first['appearances'] %> movies seen)
        </p>

      <% end %>
    <% if @fav_director.present? %>
      <p>
        <strong>Favorite Director:</strong>
        <%= @fav_director.first['director'] %>  (<%= @fav_director.first['num_movies_seen'] %> movies seen)
      </p>
      <% end %>
    </div>
    <div class="col-md-6">
      <p>
        <strong>Top Genres:</strong>
      </p>
      <ul>
        <% @top_genres.each do |genre| %>
          <li><%= genre['name'] %> (<%= genre['num_movies_seen'] %> movies seen)</li>
        <% end %>
      </ul>
    </div>
  </div>
</div>