config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :watchlists

  root 'users#login'

  resources :users
  get 'login', to: 'users#login'
  post 'login', to: 'users#authenticate'
  get 'logout', to: 'users#logout'


  resources :movies do
    resources :reviews, only: [:index, :new, :create] # Include new and create actions for reviews
  end

  # Custom route for searching movies
  get '/search_movies', to: 'movies#search', as: 'search_movies'
  get '/search', to: 'movies#search', as: 'search'

  resources :seens, except: [:create, :destroy]
  post '/seens', to: 'seens#create', as: 'create_seen'
  delete '/seens/:id', to: 'seens#destroy', as: 'destroy_seen'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <ul class="navbar-left">
     <% if @current_user %>
    <li><%= link_to 'Logout', logout_path, class: 'navbar-links', data: { confirm: 'Are you sure you want to log out?' } %></li>

     
   <%else %>
    <li><%= link_to 'Login', root_path, class: 'navbar-links' %></li>
  <% end %>
   
    <li><%= link_to 'Search', search_movies_path, class: 'navbar-links' %></li>
    <li><%= link_to 'My Watchlist', watchlists_path, class: 'navbar-links' %></li>
    <li><%= link_to 'My Movies', seens_path, class: 'navbar-links' %></li>
    <% if @current_user %>
      <li><%= link_to 'My Stats', user_path(@current_user.userid), class: 'navbar-links' %></li>
    <% end %>
  </ul>
  <% if @current_user %>
    <ul class="navbar-right">
      <li>
        <%= User.find_by(userid: @current_user.userid).name %>
        <!-- Add your links for authenticated users here -->
      </li>
    </ul>
  <% end %>
</nav>